name: Semver
description: Substitute variables for JSON/XML - first release will support JSON
inputs:
  repo:
    required: false
    default: ${{ github.repository }}
  token:
    required: false
    default: ${{ github.token }}  
  org:
    required: false
    default: ${{ github.repository_owner }}
  issue-id:
    required: false
    default: ''
  issue-number:
    required: false
    default: 0
  pid:
    required: true
    default: 1
  
  
  
outputs:
  version:
    description: version
runs:
  using: "node16"
  main: src/index.js